# Generated by Django 3.2.12 on 2022-04-19 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma', models.IntegerField(default=0)),
                ('about', models.TextField(max_length=256, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('showdead', models.BooleanField(default=False)),
                ('noprocrast', models.BooleanField(default=False)),
                ('maxvisit', models.IntegerField(default=20)),
                ('minaway', models.IntegerField(default=180)),
                ('delay', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
