# Generated by Django 3.2.12 on 2022-04-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220414_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.IntegerField(null=True),
        ),
    ]
