# Generated by Django 3.2.12 on 2022-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='votes',
            field=models.BigIntegerField(null=True),
        ),
    ]
