# Generated by Django 3.2.12 on 2022-05-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
